### ISSUE TITLE
Build instructions for dll

### ISSUE THREAD

**Issue by requiemninja** [0dm/DS3DebugFPS#1]
I've been trying to compile the dll for a little while and can't quite get it to compile correctly, as when I try to compile against mingw32 gcc will spit out errors such as `asm.s:16: Error: bad register name %r9` but under mingw64 it fails with `/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmsvcrt`

So I was wondering if you could share what environment you compile it under?

**Comment by 0dm** [comment]
I'm compiling with mingw64, GCC version 8.1.0.
Target: x86_64-w64-mingw32
You could try building without -lmsvcrt, it _should_ still work.

**Comment by requiemninja** [comment]
That worked, thank you. I thought I attempted that at one point, but I guess I didn't.
