### ISSUE TITLE
When sprinting, if I am obstructed by something my character is slowed while continuing the sprint animation

### ISSUE THREAD

**Issue by alshdavid** [0dm/DS3DebugFPS#2]
If I start sprinting then run into a wall (that doesn't break the sprint animation) and I point away from the wall, expecting to sprint away, the sprint speed is the same as walking but the character animation is showing I am sprinting.

**Comment by 0dm** [comment]
I've known about this bug for a while, I haven't been able to come up with a good solution. It's not really the mod's fault, the game just isn't made to run at higher framerates.

**Comment by alshdavid** [comment]
Yeah I had a feeling that was the case. Thanks for your work on this mod though - enjoying the game as we speak!
