### ISSUE TITLE
Updated for 1.15.1 [Not work for me]

### ISSUE THREAD

**Issue by Milor123** [0dm/DS3DebugFPS#3]
Hi dude, I am trying to unlock my FPS, but it not work in my DarkSouls 1.15. Then i use you old version and both work nive (Dll And exe) I am in Intel core  i7 4790k, GPU AMD.  

Tested with a unpacked game (modded textures and gameplay mod.).
Please tell me if you need something for debug it.

**Comment by LittleZen** [comment]
we are two on

Ryzen 5 2600
RTX2060

**Comment by Milor123** [comment]
> we are two on
> 
> Ryzen 5 2600 RTX2060

I solve it using a old version. Try use it https://github.com/0dm/DS3DebugFPS/releases/tag/1.1

**Comment by LittleZen** [comment]
Since the plug-in seems to be still actively developed, and the issue is NOT solved, you should leave the issue opened!
