### ISSUE TITLE
Can't get this to work whatsoever...

### ISSUE THREAD

**Issue by Cees381** [0dm/DS3DebugFPS#4]
I've tried following the 'guide', but eh, what could I be doing wrong? 😭

![Game - 2022-12-26_14-34](https://user-images.githubusercontent.com/85225959/209554810-66ccacd3-d394-485b-b741-977ff3fe5c23.jpg)

**Comment by 0dm** [comment]
sorry for the late response! try removing the other mods and see if the issue persists / verify game cache. the mod will be updated soon for the latest app version.
